{
 "title": "Celery Monitoring",
 "tags": [
  "easytrax",
  "celery",
  "queues"
 ],
 "time": { "from": "now-1d", "to": "now" },
 "panels": [
  {
   "title": "Alarm worker queue",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "celery_queue_length{queue_name=\"enterprise_alarm_report\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Telemetry worker queue",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 9, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "celery_queue_length{queue_name=\"enterprise_telemetry\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trip worker queue",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 18, "w": 8, "h": 10 },
   "targets": [
    {
     "expr": "celery_queue_length{queue_name=\"enterprise-command\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Report worker queue",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 18, "w": 8, "h": 10 },
   "targets": [
    {
     "expr": "celery_queue_length{queue_name=\"enterprise_periodic\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notification worker queue",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 18, "w": 8, "h": 10 },
   "targets": [
    {
     "expr": "celery_queue_length{queue_name=\"sms-queue\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}