version: '3.8'
services:
  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    volumes:
      - ./conf/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./parsers/parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - /srv/workers/easytrax-platform-worker/tmp/celery/efollowr_alarm.log:/var/log/efollowr_alarm.log:ro
    restart: unless-stopped
    network_mode: host
